### ISSUE TITLE
Unable to start

### ISSUE THREAD

**Issue by peduarte** [netlify/create-react-app-lambda#11]
Hey 👋 

I'm not able to get this to run properly. The React App runs fine, but seems the netlify lambda is not working. 

Steps to reproduce:
1. Clone this repo
2. Run `yarn`
3. Run `yarn start`

When I do `yarn start` the CRA app launches. I click on the `Call Lambda` button and:
![image](https://user-images.githubusercontent.com/372831/49120791-00665700-f2a6-11e8-8a4a-9dc94c079f43.png)

This is the error I get if I do `yarn start:lambda` directly:
![image](https://user-images.githubusercontent.com/372831/49120784-f9d7df80-f2a5-11e8-9bf7-407dd0e7bd3a.png)

I also tried running `yarn build:lambda` but get this:
```
ERROR in ./hello.js
Module build failed (from /Users/peduarte/Projects/playground/create-react-app-lambda/node_modules/babel-loader/lib/index.js):
Error: Cannot find module '@babel/plugin-transform-object-assign' from '/Users/peduarte/Projects/playground/create-react-app-lambda'
```

Could be related to this... https://github.com/dominictarr/event-stream/issues/115 ? 🤔

Im not sure what's going on, would appreciate any guidance 🙏

Thanks 👊

**Comment by peduarte** [comment]
🙄Ermm, because of past negative experiences with Yarn, I decided to delete `node_modules/` and `yarn.lock` and try it all again with `npm`.

1. `npm install`
2. `npm start`

And not it's all running as expected. So weird! 

Would love it anyone could try and replicate this for me though.

**Comment by sw-yx** [comment]
thanks for the report! i cannot replicate this. using `yarn` works and clicking `Call Lambda` works as expected. what version of yarn are you doing?

**Comment by peduarte** [comment]
@sw-yx hey! I've got:
- `yarn`- `1.3.2`
-`node` `10.10.0`

I've upgraded `yarn` to `1.12.1` and I after running `yarn` I get this:
![image](https://user-images.githubusercontent.com/372831/49149591-61237d00-f302-11e8-8f58-901e9aeca91f.png)

I've now upgraded `node` to `11.3.0` and I get the same error as above ☝️

**Comment by sw-yx** [comment]
yea flatmap caused problems for me today too :( closing since it seems resolved.

**Comment by peduarte** [comment]
Hey, weirdly enough it's all happening again.

```
~/Projects/playground/create-react-app-lambda master ☉
▷  yarn start:lambda
yarn run v1.12.3
$ netlify-lambda serve src/lambda
netlify-lambda: Starting server
Lambda server is listening on 9000
Unhandled rejection Error: Cannot find module '/Users/peduarte/Projects/playground/create-react-app-lambda/lambda/hello'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
    at Function.resolve (internal/modules/cjs/helpers.js:32:19)
    at Object.clearCache (/Users/peduarte/Projects/playground/create-react-app-lambda/node_modules/netlify-lambda/lib/serve.js:111:36)
    at /Users/peduarte/Projects/playground/create-react-app-lambda/node_modules/netlify-lambda/bin/cmd.js:38:16
    at Array.forEach (<anonymous>)
    at Watching.handler (/Users/peduarte/Projects/playground/create-react-app-lambda/node_modules/netlify-lambda/bin/cmd.js:37:32)
    at compiler.hooks.done.callAsync (/Users/peduarte/Projects/playground/create-react-app-lambda/node_modules/netlify-lambda/node_modules/webpack/lib/Watching.js:98:9)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/peduarte/Projects/playground/create-react-app-lambda/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/peduarte/Projects/playground/create-react-app-lambda/node_modules/tapable/lib/Hook.js:154:20)
    at Watching._done (/Users/peduarte/Projects/playground/create-react-app-lambda/node_modules/netlify-lambda/node_modules/webpack/lib/Watching.js:97:28)
    at onCompiled (/Users/peduarte/Projects/playground/create-react-app-lambda/node_modules/netlify-lambda/node_modules/webpack/lib/Watching.js:47:18)
    at hooks.afterCompile.callAsync.err (/Users/peduarte/Projects/playground/create-react-app-lambda/node_modules/netlify-lambda/node_modules/webpack/lib/Compiler.js:552:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/peduarte/Projects/playground/create-react-app-lambda/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/peduarte/Projects/playground/create-react-app-lambda/node_modules/tapable/lib/Hook.js:154:20)
    at compilation.seal.err (/Users/peduarte/Projects/playground/create-react-app-lambda/node_modules/netlify-lambda/node_modules/webpack/lib/Compiler.js:549:30)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/peduarte/Projects/playground/create-react-app-lambda/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
```

with `node - v11.3.0` and `yarn - 1.12.3`

**Comment by sw-yx** [comment]
i didn't have to, i cloned this repo on a fresh machine and it "just worked".

leaving this open for now incase someone else can replicate

**Comment by peduarte** [comment]
@sw-yx I see. You know what, I honestly don't think it's anything to do with this. I'm gonna continue to debug it and raise the issues with the corresponding libraries. 

Thanks for this man! 👊

**Comment by kmalillos** [comment]
> i didn't have to, i cloned this repo on a fresh machine and it "just worked".
> 
> leaving this open for now incase someone else can replicate

I'm having this issue as well... so when you tried on a "fresh" (different?) machine, it worked? so it was just on the computer you were working on, you think?

**Comment by sw-yx** [comment]
@kmalillos feel free to open a new issue, i think this one getting a bit crowded.
