### ISSUE TITLE
Can't build:lambda once ejected

### ISSUE THREAD

**Issue by visuallization** [netlify/create-react-app-lambda#13]
Hey guys,

When ejecting the app and do nothing else than that, then yarn `build:lambda` won't work. It throws the following error:

`Error: Cannot find module '@babel/plugin-transform-object-assign'`

When I install the missing module @babel/plugin-transform-object-assign and then build again it throws: 

```
ERROR in ./subscribe.js
Module build failed (from D:/Documents/web/git/lambda_mailchimp/node_modules/babel-loader/lib/index.js):
Error: [BABEL] D:\Documents\web\git\lambda_mailchimp\src\lambda\subscribe.js: Using `babel-preset-react-app` requires that you specify `NODE_ENV` or `BABEL_ENV` environment variables. Valid values are "development", "test", and "production". Instead, received: undefined. (While processing: "D:\\Documents\\web\\git\\lambda_mailchimp\\node_modules\\babel-preset-react-app\\index.js")
    at module.exports (D:\Documents\web\git\lambda_mailchimp\node_modules\babel-preset-react-app\create.js:48:11)
    at module.exports (D:\Documents\web\git\lambda_mailchimp\node_modules\babel-preset-react-app\index.js:19:10)
    at loadDescriptor (D:\Documents\web\git\lambda_mailchimp\node_modules\@babel\core\lib\config\full.js:165:14)
    at cachedFunction (D:\Documents\web\git\lambda_mailchimp\node_modules\@babel\core\lib\config\caching.js:33:19)
    at loadPresetDescriptor (D:\Documents\web\git\lambda_mailchimp\node_modules\@babel\core\lib\config\full.js:235:63)
    at config.presets.reduce (D:\Documents\web\git\lambda_mailchimp\node_modules\@babel\core\lib\config\full.js:77:21)
    at Array.reduce (<anonymous>)
    at recurseDescriptors (D:\Documents\web\git\lambda_mailchimp\node_modules\@babel\core\lib\config\full.js:74:38)
    at loadFullConfig (D:\Documents\web\git\lambda_mailchimp\node_modules\@babel\core\lib\config\full.js:108:6)
    at process.nextTick (D:\Documents\web\git\lambda_mailchimp\node_modules\@babel\core\lib\transform.js:28:33)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
Done in 2.87s.
```

I am using Windows 10.

Any ideas why this is happening?

Cheers

**Comment by visuallization** [comment]
Okay so I made it work. You can check out the working ejected example here: https://github.com/visuallization/mailchimp-lambda/tree/ejected

What I have basically done was calling `yarn start:lambda` and `yarn build:lambda` in a similiar manner how `yarn start:app` is working.

So I created 2 new files under` scripts/`, namely `start_lambda.js` and `build_lambda.js`

Here is the source:

start_lambda.js

```
process.env.BABEL_ENV = 'development';
process.env.NODE_ENV = 'development';

const exec = require('child_process').exec;

exec('netlify-lambda serve src/lambda',
  function(err, stdout, stderr) {
    if (err) throw err;
    else console.log(stdout);
});
```

build_lambda.js

```
process.env.BABEL_ENV = 'production';
process.env.NODE_ENV = 'production';

const exec = require('child_process').exec;

exec('netlify-lambda build src/lambda',
  function(err, stdout, stderr) {
    if (err) throw err;
    else console.log(stdout);
});

```

So I am setting NODE_ENV and BABEL_ENV in these files and call them in `package.json` like this: 

```
"start:lambda": "node scripts/start_lambda.js",
"build:lambda": "node scripts/build_lambda.js",
```

I also had to install 3 more modules: 

```
"@babel/plugin-transform-object-assign": "^7.0.0",
"@babel/plugin-transform-react-jsx": "^7.1.6",
"@babel/plugin-transform-react-jsx-source": "^7.0.0",
```

But your compiler will tell you anyways.

Hope this helps someone.

Cheers

**Comment by sw-yx** [comment]
hi @visuallization, sorry you experienced this and thanks for filing an issue. i confess i've never ejected a c-r-a-l project. wanna propose a PR for fixing this?

**Comment by visuallization** [comment]
@sw-yx yeah I might be able to look into this but curently I am pretty busy with my job and project. Will create a PR once I find the time.
